language: node_js
node_js:
- "node"
cache: yarn
install:
- yarn install
- yarn global add coveralls

script:
- yarn build
- yarn jest --config node/jest.json --coverage --coverageReporters=text-lcov | coveralls
